### PR TITLE
support parsing BUNDLED WITH

### PR DESCRIPTION
**Pull request by akostadinov**
part of
https://issues.redhat.com/browse/STONEBLD-1055

### CODE REVIEW

**Comment by chmeliik** [comment]
@akostadinov would you mind proposing this change upstream first? https://github.com/nexB/scancode-toolkit/blob/develop/src/packagedcode/gemfile_lock.py

This repo is mostly a "vendored" copy of the ScanCode implementation, we would like to avoid drift

**Comment by chmeliik** [comment]
(and thanks for your interest in contributing :tada: )

**Comment by akostadinov** [comment]
Started a PR https://github.com/nexB/scancode-toolkit/pull/3444

I guess it will require some more work so any support there would be appreciated.

**Comment by chmeliik** [comment]
I see that the upstream PR is merged, thanks! :tada: 

Porting your changes (and other missing changes) in #3

**Pull request closed without merging**
